modLoader = "javafml"
loaderVersion = "[2,)"
license = "Powered by Hummel009"

logoFile = "logo.png"
[[mods]]
modId = "trop"
version = "23.06.10"
displayName = "The Rings of Power"
credits = "Hummel009"
authors = "Hummel009"
description = '''This mod adds Rings of Power from the Lord of the Rings to Minecraft'''
[[dependencies.trop]]
modId = "minecraft"
mandatory = true
versionRange = "[1.13.2]"
ordering = "NONE"
side = "BOTH"