modLoader = "javafml"
loaderVersion = "[3,)"
license = "Powered by Hummel009"

[[mods]]
modId = "trop"
version = "23.06.13"
displayName = "The Rings of Power"
logoFile = "logo.png"
credits = "Hummel009"
authors = "Hummel009"
description = '''This mod adds Rings of Power from the Lord of the Rings to Minecraft'''
[[dependencies.trop]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"