modLoader="javafml" 
loaderVersion="[3,)" 
license="Powered by Hummel009"

[[mods]]
modId="trop"
version="4.0"
displayName="The Rings of Power"
logoFile="logo.png"
credits="Hummel009"
authors="Hummel009"
description='''This mod adds Rings of Power from the Lord of the Rings to Minecraft'''
[[dependencies.trop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"