name: Java CI with Gradle
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  build1_3_2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: build
          build-root-directory: ./1.3.2
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-artifact-1-3-2
          path: ./1.3.2/build/libs/*.jar
  build1_4_7:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: build
          build-root-directory: ./1.4.7
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-artifact-1-4-7
          path: ./1.4.7/build/libs/*.jar
  build1_5_2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: build
          build-root-directory: ./1.5.2
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-artifact-1-5-2
          path: ./1.5.2/build/libs/*.jar
  build1_6_4:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: build
          build-root-directory: ./1.6.4
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-artifact-1-6-4
          path: ./1.6.4/build/libs/*.jar
  build1_7_10:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: build
          build-root-directory: ./1.7.10
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-artifact-1-7-10
          path: ./1.7.10/build/libs/*.jar
  build1_8_9:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: build
          build-root-directory: ./1.8.9
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-artifact-1-8-9
          path: ./1.8.9/build/libs/*.jar
  build1_9_4:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: build
          build-root-directory: ./1.9.4
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-artifact-1-9-4
          path: ./1.9.4/build/libs/*.jar
  build1_10_2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: build
          build-root-directory: ./1.10.2
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-artifact-1-10-2
          path: ./1.10.2/build/libs/*.jar
  build1_11_2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: build
          build-root-directory: ./1.11.2
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-artifact-1-11-2
          path: ./1.11.2/build/libs/*.jar
  build1_12_2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: build
          build-root-directory: ./1.12.2
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-artifact-1-12-2
          path: ./1.12.2/build/libs/*.jar
  build1_13_2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: build
          build-root-directory: ./1.13.2
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-artifact-1-13-2
          path: ./1.13.2/build/libs/*.jar
  build1_14_4:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: build
          build-root-directory: ./1.14.4
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-artifact-1-14-4
          path: ./1.14.4/build/libs/*.jar
  build1_15_2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: build
          build-root-directory: ./1.15.2
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-artifact-1-15-2
          path: ./1.15.2/build/libs/*.jar
  build1_16_5:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: build
          build-root-directory: ./1.16.5
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-artifact-1-16-5
          path: ./1.16.5/build/libs/*.jar
  build1_17_1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: build
          build-root-directory: ./1.17.1
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-artifact-1-17-1
          path: ./1.17.1/build/libs/*.jar
  build1_18_2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: build
          build-root-directory: ./1.18.2
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-artifact-1-18-2
          path: ./1.18.2/build/libs/*.jar
  build1_19_4:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: build
          build-root-directory: ./1.19.4
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-artifact-1-19-4
          path: ./1.19.4/build/libs/*.jar
  build1_20_1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: build
          build-root-directory: ./1.20.1
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-artifact-1-20-1
          path: ./1.20.1/build/libs/*.jar
