name: Java CI with Gradle
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  build-forge-3-6:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [ '1.3.2', '1.4.7', '1.5.2', '1.6.4' ]
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
        with:
          cache-disabled: true
      - name: Build with Gradle
        working-directory: ./forge
        run: ./gradlew :${{matrix.version}}:build
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: archive-forge-${{matrix.version}}
          path: ./forge/${{matrix.version}}/build/libs/*.jar
  build-forge-7:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [ '1.7.10' ]
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
        with:
          cache-disabled: true
      - name: Build with Gradle
        working-directory: ./forge
        run: ./gradlew :${{matrix.version}}:build
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: archive-forge-${{matrix.version}}
          path: ./forge/${{matrix.version}}/build/libs/*.jar
  build-forge-11-12:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [ '1.8.9', '1.9.4', '1.10.2', '1.11.2', '1.12.2' ]
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
        with:
          cache-disabled: true
      - name: Build with Gradle
        working-directory: ./forge
        run: ./gradlew :${{matrix.version}}:build
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: archive-forge-${{matrix.version}}
          path: ./forge/${{matrix.version}}/build/libs/*.jar
  build-forge-13-20:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [ '1.13.2', '1.14.4', '1.15.2', '1.16.5', '1.17.1', '1.18.2', '1.19.4', '1.20.6' ]
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
        with:
          cache-disabled: true
      - name: Build with Gradle
        working-directory: ./forge
        run: ./gradlew :${{matrix.version}}:build
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: archive-forge-${{matrix.version}}
          path: ./forge/${{matrix.version}}/build/libs/*.jar
  build-fabric:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [ '1.14.4', '1.15.2', '1.16.5', '1.17.1', '1.18.2', '1.19.4', '1.20.6' ]
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
        with:
          cache-disabled: true
      - name: Build with Gradle
        working-directory: ./fabric
        run: ./gradlew :${{matrix.version}}:build
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: archive-fabric-${{matrix.version}}
          path: ./fabric/${{matrix.version}}/build/libs/*.jar
  merge-forge:
    runs-on: windows-latest
    needs: [ build-forge-3-6, build-forge-7, build-forge-8-12, build-forge-13-20 ]
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@main
        with:
          name: archive-forge
          pattern: archive-forge-*
          delete-merged: true
  merge-fabric:
    runs-on: windows-latest
    needs: build-fabric
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@main
        with:
          name: archive-fabric
          pattern: archive-fabric-*
          delete-merged: true